version: 2.1

jobs:
  build:
    docker:
      - image: debian:stretch

    parameters: &COMMON_PARAMS
      config:
        type: string

    steps:
      - checkout

      - run:
          name: Make artifact dir
          command: mkdir -p artifacts

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Run build script
          command: "./build.sh -t build -c << parameters.config >> | tee artifacts/build.log"

      # - persist_to_workspace:
      #     root: artifacts
      #     paths:
      #       - ./*

  test:
    docker:
      - image: debian:stretch

    parameters: *COMMON_PARAMS

    steps:
      # - attach_workspace:
      #     at: artifacts

      - checkout

      # - run:
      #     name: Check Artifact
      #     command: cat artifacts/build.log

      - run:
          name: Run tests
          command: ./build.sh -t test -c << parameters.config >>

  upload:
    docker:
      - image: debian:stretch

    parameters: *COMMON_PARAMS

    steps:
      - checkout

      - run:
          name: Upload
          command: ./build.sh -t upload -c << parameters.config >>


workflows:
  pr:
    jobs:
      - build:
          name: PrDebugBuild
          config: debug
      - test:
          name: PrDebugTest
          config: debug
          requires:
            - PrDebugBuild
          filters: &COMMON_PR_FILTERS
            branches:
              only: /feature\/.*/

      - build:
          name: PrReleaseBuild
          config: release
      - test:
          name: PrReleaseTest
          config: release
          requires:
            - PrReleaseBuild
          filters: *COMMON_PR_FILTERS

  commit:
    jobs:
      - build:
          name: CommitReleaseBuild
          config: release
          filters: &COMMON_COMMIT_FILTERS
            branches:
              only: master
      - upload:
          config: release
          requires:
            - CommitReleaseBuild
          filters: *COMMON_COMMIT_FILTERS
